# Generated by Django 4.1.7 on 2023-08-08 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 21, 54, 27, 252659, tzinfo=datetime.timezone.utc)),
        ),
    ]
