# Generated by Django 4.1.7 on 2023-08-08 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_entry_blog_alter_entry_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 21, 56, 2, 500245, tzinfo=datetime.timezone.utc)),
        ),
    ]
